import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/Header";
import Intro from "../components/Intro";
import AboutMe from "../components/AboutMe";
import CareerPath from "../components/CareerPath";
import Portfolios from "../components/Portfolios";
import Skills from "../components/Skills";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Soma Ikeda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Header section */}
        <Header />
        <article>
          {/* Introduction section */}
          <Intro />
          {/* About Me section */}
          <AboutMe />
          {/* Career Path */}
          <CareerPath />
          {/* Portfolio senction  */}
          <Portfolios />
          {/* Skills section */}
          <Skills />
          {/* Contact section */}
          <Contact />
        </article>
        {/* Footer section */}
        <Footer />
      </main>
    </div>
  );
};

export default Home;
