import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/Header';
import Intro from '../components/Intro';
import Skills from '../components/Skills';
import Portfolios from '../components/Portfolios';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

const Home: NextPage = () => {

  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Header section */}
        <Header />
        <article>
          {/* Introduction section */}
          <Intro />
          {/* Skills section */}
          <Skills />
          {/* Portfolio senction  */}
          <Portfolios />
          {/* Contact section */}
          <Contact />
        </article>
        {/* Footer section */}
        <Footer />
      </main>
    </div>
  )
}

export default Home;
