import Head from 'next/head';
import React from 'react';
import Footer from '../Footer';
import Header from '../Header';

interface AppLyoutProps {
    tabTitle: string;
    children: JSX.Element | JSX.Element[];
}

const AppLyout: React.FC<AppLyoutProps> = ({
    tabTitle,
    children
}) => {
    return (
        <div>
            <Head>
                <title>{tabTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {/* Header section */}
                <Header />
                <article>
                    {children}
                </article>
                {/* Footer section */}
                <Footer />
            </main>
        </div>
    );
};

export default AppLyout;
